In [1]:
from mart_controller import MART_Evaluator
from PIL import Image
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
import joblib

In [2]:
IMG_DIR = '/mnt/sda/hong01-data/MART_DATA/OUTPUT_MERGED/AUTOGRAPHER'
PANDAS_DIR = '/mnt/sda/hong01-data/MART_DATA/OUTPUT_MERGED/PANDAS'

MODEL_NAME = 'EFFICIENT-B4'
CROP_SIZE = 224
CHECKPOINT = 'RUN_0_Unfreeze/EFFICIENT-B4-18082020-020739.pth.tar'
HIDDEN_SIZE = 1024
BATCH_NORM = False
    
model_info = {}
model_info['model_name'] = MODEL_NAME
model_info['crop_size'] = CROP_SIZE
model_info['checkpoint'] = CHECKPOINT
model_info['hidden_size'] = HIDDEN_SIZE
model_info['batch_norm'] = BATCH_NORM

evaluator = MART_Evaluator(model_info)

all_img_files = sorted(os.listdir(IMG_DIR))

Loaded pretrained weights for efficientnet-b4
LOAD PRETRAINED MODEL AT RUN_0_Unfreeze/EFFICIENT-B4-18082020-020739.pth.tar


## TRY THE CODE

In [24]:
TXT_FILE = 'dataset/val.txt'

loss, acc = evaluator.evaluate(IMG_DIR, TXT_FILE)
(loss, acc)

(0.8546260260045528, 0.9017341040462428)

In [25]:
img_path = f"{IMG_DIR}/1005_trainB_act17_4.jpg"
pred_lbl, probs_lbl = evaluator.test_image(img_path, props=True) # remember act = label+1

In [26]:
pred_lbl

16

In [27]:
probs_lbl

array([2.1052938e-07, 3.3188870e-05, 8.3061364e-05, 1.2945433e-06,
       8.5043384e-06, 5.5669909e-07, 2.3099426e-05, 1.2240148e-06,
       3.4870263e-06, 6.4895437e-07, 5.6167302e-04, 2.2210679e-06,
       1.0234877e-01, 6.5412465e-04, 1.4623778e-05, 7.7470195e-06,
       8.5550719e-01, 3.9434277e-02, 9.8404140e-05, 1.2157230e-03],
      dtype=float32)

In [28]:
ranking_lbl = np.argsort(probs_lbl)[::-1] # descending
ranking_score = probs_lbl[ranking_lbl]

In [18]:
ranking_lbl

array([16, 12, 17, 19, 13, 10, 18,  2,  1,  6, 14,  4, 15,  8, 11,  3,  7,
        9,  5,  0])

In [19]:
ranking_score

array([8.5550719e-01, 1.0234877e-01, 3.9434277e-02, 1.2157230e-03,
       6.5412465e-04, 5.6167302e-04, 9.8404140e-05, 8.3061364e-05,
       3.3188870e-05, 2.3099426e-05, 1.4623778e-05, 8.5043384e-06,
       7.7470195e-06, 3.4870263e-06, 2.2210679e-06, 1.2945433e-06,
       1.2240148e-06, 6.4895437e-07, 5.5669909e-07, 2.1052938e-07],
      dtype=float32)

In [29]:
probs_lbl.shape

(20,)

## MAKE THE PREDICTION 

In [7]:
dataset = 'trainA' # trainA, trainB, test
data = pd.read_csv(f"{PANDAS_DIR}/{dataset}.csv")

In [8]:
data.head(3)

Unnamed: 0  sub_id event_id  source  data_HR_activity_median  \
0           0    1001    act01  trainA                84.507042   
1           1    1001    act02  trainA                83.333333   
2           2    1001    act03  trainA                83.920188   

   data_HR_activity_min  data_HR_activity_max  data_HR_activity_average  \
0             76.923077            100.000000                 84.577495   
1             71.428571            100.000000                 82.631420   
2             76.923077             90.909091                 84.207147   

   data_HR_activity_std  data_HR_activity_len  ...  \
0              3.933112                    90  ...   
1              5.642256                    89  ...   
2              2.827778                    90  ...   

   data_AUTOGRAPHER_RESNET_max_buckeye, horse chestnut, conker  \
0                                           0.000728             
1                                           0.001809             
2                                           0.000996             

   data_AUTOGRAPHER_RESNET_max_coral fungus  \
0                                  0.000090   
1                                  0.000228   
2                                  0.000154   

   data_AUTOGRAPHER_RESNET_max_agaric  data_AUTOGRAPHER_RESNET_max_gyromitra  \
0                            0.000920                               0.000048   
1                            0.002908                               0.000167   
2                            0.002684                               0.000104   

   data_AUTOGRAPHER_RESNET_max_stinkhorn, carrion fungus  \
0                                           0.000100       
1                                           0.000224       
2                                           0.000201       

   data_AUTOGRAPHER_RESNET_max_earthstar  \
0                               0.000287   
1                               0.000654   
2                               0.000685   

   data_AUTOGRAPHER_RESNET_max_hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa  \
0                                           0.000317                                                       
1                                           0.000971                                                       
2                                           0.000620                                                       

   data_AUTOGRAPHER_RESNET_max_bolete  \
0                            0.000290   
1                            0.000937   
2                            0.000566   

   data_AUTOGRAPHER_RESNET_max_ear, spike, capitulum  \
0                                           0.001594   
1                                           0.007302   
2                                           0.006093   

   data_AUTOGRAPHER_RESNET_max_toilet tissue, toilet paper, bathroom tissue  
0                                           0.001767                         
1                                           0.013306                         
2                                           0.005520                         

[3 rows x 3112 columns]

In [5]:
len(data)

140

In [6]:
sub_id = list(data['sub_id'])
event_id = list(data['event_id'])
task_id = [f"{x}_{y}" for x, y in zip(sub_id, event_id)]
task_id = task_id[0:10] # take the small
task_id[0:5]

['1001_act01', '1001_act02', '1001_act03', '1001_act04', '1001_act05']

In [9]:
list_probs = np.zeros((len(task_id), 20))
# start loop
for idx_task, task in tqdm(enumerate(task_id)):
    if dataset == 'trainA' or dataset == 'trainB':
        task = task.split('_')
        task = f"{task[0]}_{dataset}_{task[1]}"
    task_imgs = [x for x in all_img_files if task in x]
    task_probs = np.zeros((len(task_imgs), 20))
    for idx, img in enumerate(task_imgs):
        img_path = f"{IMG_DIR}/{img}"
        pred_lbl, probs_lbl = evaluator.test_image(img_path, props=True) # remember act = label+1
        task_probs[idx] = probs_lbl
    task_mean_probs = np.mean(task_probs, axis=0)
    list_probs[idx_task] = task_mean_probs
# end loop

10it [00:06,  1.57it/s]


## GENERATE SUBMISSION FILE

In [3]:
import joblib
import os
import numpy as np
import pandas as pd

RUN = 'test' # trainA, trainB, test
PANDAS_DIR = '/mnt/sda/hong01-data/MART_DATA/OUTPUT_MERGED/PANDAS'
data = pd.read_csv(f"{PANDAS_DIR}/{RUN}.csv")
sub_id = list(data['sub_id'])
event_id = list(data['event_id'])
task_id = [f"{x}_{y}" for x, y in zip(sub_id, event_id)]
task_id_np = np.asarray(task_id)
probs = joblib.load(f'joblib_files/act_probs_{RUN}_RUN_0_Unfreeze.joblib')

In [6]:
probs.shape

(140, 20)

In [6]:
submission = "group_id: group50 ouroboros\n"

for act in range(20):
    probs_act = probs[:, act]
    highest_subj = np.zeros(7)
    for i in range(7):
        subj_act_probs = probs_act[(i*20):((i+1)*20)]
        highest_index = np.argsort(subj_act_probs)[::-1][0]
        highest_index += (i*20)
        highest_subj[i] = highest_index
    highest_subj = highest_subj.astype(int)
    highest_subj_list = list(highest_subj)
    remain_subj_act = [x for x in range(len(task_id)) if x not in highest_subj_list]
    remain_subj_act = np.asarray(remain_subj_act)
    highest_subj_score = probs_act[highest_subj]
    remain_subj_score = probs_act[remain_subj_act]
    
    h_index = np.argsort(highest_subj_score)[::-1]
    h_map_index = highest_subj[h_index]
    r_index = np.argsort(remain_subj_score)[::-1]
    r_map_index = remain_subj_act[r_index]
    final_index = np.concatenate((h_map_index, r_map_index))
    task_ranking = task_id_np[final_index]
    task_score = probs_act[final_index]
    
    task_ranking_list = list(task_ranking)
    if act < 9:
        act_str = f"act0{act+1}"
    else:
        act_str = f"act{act+1}"
    for task in task_ranking_list:
        submission += f"{act_str} {task}\n"

submission_write = open(f"Submission/submission_{RUN}.txt", "w")
submission_write.write(submission)
submission_write.close()

print('DONE')

DONE
